apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-profile
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-retain-custom"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
      iops: "4000"