apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-01-24T17:34:50Z
  generation: 1
  labels:
    run: portal-deployment
  name: portal-deployment
  namespace: default
  resourceVersion: ""
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/portal-deployment
  uid: e10f7c3f-012c-11e8-9ac6-a67223d60947
spec:
  replicas: 1
  selector:
    matchLabels:
      run: portal-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: portal-deployment
    spec:
      containers:
      - image: <registry.domain.bluemix.net>/<CloudFoundrySpace>/dxen:v90
        imagePullPolicy: IfNotPresent
        name: portal-deployment
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /wps/portal
            port: 30005
          initialDelaySeconds: 180
          timeoutSeconds: 35
          periodSeconds: 40
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - mountPath: /opt/IBM/WebSphere/wp_profile
          name: portal-profile
      volumes:
      - name: portal-profile
        persistentVolumeClaim:
          claimName: portal-profile
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-01-24T17:34:50Z
    lastUpdateTime: 2018-01-24T17:34:50Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1