apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 
    generation: 1
    labels:
      run: portal-deployment
    name: portal-deployment
    namespace: default
    resourceVersion: "2177"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/portal-deployment
    uid: 59596db1-b281-11e7-874f-02f1216da333
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: portal-deployment
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: portal-deployment
      spec:
        containers:
        - image: registry.ng.bluemix.net/<CloudFoundrySpace>/dxen:v90
          imagePullPolicy: IfNotPresent
          name: portal-deployment
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /wps/portal
              port: 30005
            initialDelaySeconds: 180
            timeoutSeconds: 35
            periodSeconds: 40
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
          - mountPath: /opt/IBM/WebSphere/wp_profile
            name: portal-profile
        volumes:
        - name: portal-profile
          persistentVolumeClaim:
            claimName: portal-profile
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2017-10-16T14:50:27Z
      lastUpdateTime: 2017-10-16T14:50:27Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
