apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 
  labels:
    run: portal-deployment
  name: portal-deployment
  namespace: default
  resourceVersion: ""
  selfLink: /api/v1/namespaces/default/services/portal-deployment
  uid: de7f63ed-cbd9-11e7-bcca-66a47ea06c90
spec:
  clusterIP: 172.21.18.224
  externalTrafficPolicy: Cluster
  ports:
  - name: secure-host	
    nodePort: 31212
    port: 30005
    protocol: TCP
    targetPort: 30005 
  - name: secure-admin
    nodePort: 31213
    port: 30008
    protocol: TCP
    targetPort: 30008
  - name: soap
    nodePort: 31214
    port: 30001
    protocol: TCP
    targetPort: 30001
  - name: configuration-wizard
    nodePort: 31215
    port: 31004
    protocol: TCP
    targetPort: 31004
  selector:
    run: portal-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 